#! /bin/bash

# If allowed_telnetPort is protected by a password, add the password here
TELNETPASSWORD=""
# Attribute for batterylevel in FHEM
ATTRIBUT="batterylevel"
# Use this, if you dont want the script to determine the tags on its own
LETAGS=""

# Ensure that we find gatttool in our PATH
PATH=$PATH:/bin:/usr/bin:/usr/local/bin

[ ! -z "$TELNETPASSWORD" ] && TELNETPASSWORD="$TELNETPASSWORD\n"
if [ -z "$LETAGS" ]; then
  TAGS=$(echo -e "${TELNETPASSWORD}list MODE=lan-bluetooth" | socat -t60 - TCP:127.0.0.1:7072 | grep -v "Password" | tr "[:cntrl:]" "\n" | sed 's/ //g')
else
  TAGS="$LETAGS"
fi

for tag in $TAGS
do
  [ ! -z "$1" ] && echo "Determining address for $tag ..."
  TCONFIG=$(echo -e "${TELNETPASSWORD}list $tag" | socat -t60 - TCP:127.0.0.1:7072 | tr "[:cntrl:]" "\n")
  STATE=$(echo "$TCONFIG" | awk '{if($1=="STATE")print $2}')
  if [ "$STATE" != "present" ]; then
    [ ! -z "$1" ] && echo "$tag is in state ${STATE}, no further action required"
  else
    ADDR=$(echo "$TCONFIG" | awk '{if($1=="ADDRESS") print $2}' | tr "[:cntrl:]" "\n" | sed 's/ //g')
    [ ! -z "$1" ] && echo "Fetching $ATTRIBUT for $tag ($ADDR) ..."
    LEVEL=$(gatttool -t random -b $ADDR --char-read --uuid 0x2a19 2>&1 | awk '{if($1 == "handle:") {printf("%d\n",strtonum("0x"$4))}}')
    if [ ! -z "$LEVEL" ]; then
      echo -e "${TELNETPASSWORD}setreading $tag $ATTRIBUT $LEVEL" | socat -t60 - TCP:127.0.0.1:7072 | grep -v "Password"
      [ ! -z "$1" ] && echo "Setting $ATTRIBUT for $tag to ${LEVEL}%"
    else
      [ ! -z "$1" ] && echo "No valid data found for $tag ($ADDR)"
    fi
    [ ! -z "$1" ] && echo ""
  fi
done
